// <auto-generated />
namespace SquaresandRectangles.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Loginchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Loginchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201507170201499_Login changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
